version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - odoo_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  odoo:
    build: .  # Esto le dice a Docker Compose que construya la imagen desde el Dockerfile en el directorio actual
    image: odoo-library  # El nombre de la imagen construida
    container_name: odoo_library
    ports:
      - "8069:8069"
    volumes:
      - ./odoo:/mnt/odoo  # Montar el directorio local ./odoo dentro del contenedor en /mnt/odoo
      - ./custom-addons:/mnt/custom-addons  # Montar los addons personalizados en /mnt/custom-addons
      - ./minimal_addons:/mnt/minimal_addons  # Montar los addons mínimos en /mnt/minimal_addons
      - ./odoo.conf:/mnt/odoo.conf
      - ./odoo-bin:/mnt/odoo-bin
      - ./setup:/mnt/setup
      - ./setup.cfg:/mnt/setup.cfg
      - ./setup.py:/mnt/setup.py
      - ./data:/mnt/data # data como filestore
    environment:
      - HOST=db  # Nombre del contenedor de base de datos
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - odoo_network
    depends_on:
      db:
        condition: service_healthy
        restart: true
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data:

networks:
  odoo_network:
    driver: bridge
